room_xpath_dict = {
    'B': {
        '40': '//*[@id="chart-row-166"]/div[6]/div/a',
        '41': '//*[@id="chart-row-61"]/div[9]/div/a',
        '42': '//*[@id="chart-row-62"]/div[7]/div/a',
        '43': '//*[@id="chart-row-63"]/div[9]/div/a',
        '44': '//*[@id="chart-row-64"]/div[7]/div/a',
        '45': '//*[@id="chart-row-65"]/div[5]/div/a',
        '46': '//*[@id="chart-row-66"]/div[5]/div/a',
        '51': '//*[@id="chart-row-68"]/div[10]/div/a',
        '52': '//*[@id="chart-row-69"]/div[8]/div/a',
        '53': '//*[@id="chart-row-70"]/div[8]/div/a',
        '54': '//*[@id="chart-row-71"]/div[8]/div/a',
        '55': '//*[@id="chart-row-72"]/div[8]/div/a',
        '56': '//*[@id="chart-row-73"]/div[7]/div/a',
        '57': '//*[@id="chart-row-74"]/div[8]/div/a',
        '58': '//*[@id="chart-row-75"]/div[7]/div/a',
    },
    'T': {
        '11': '//*[@id="chart-row-136"]/div[6]/div/a',
        '12': '//*[@id="chart-row-137"]/div[4]/div/a',
        '13': '//*[@id="chart-row-138"]/div[8]/div/a',
        '21': '//*[@id="chart-row-139"]/div[6]/div/a',
        '22': '//*[@id="chart-row-140"]/div[6]/div/a',
        '23': '//*[@id="chart-row-141"]/div[6]/div/a',
        '31': '//*[@id="chart-row-142"]/div[5]/div/a',
        '32': '//*[@id="chart-row-143"]/div[4]/div/a',
        '33': '//*[@id="chart-row-144"]/div[4]/div/a',
        '34': '//*[@id="chart-row-145"]/div[4]/div/a',
        '35': '//*[@id="chart-row-146"]/div[3]/div/a',
    },
    'CK': {
        '1': '//*[@id="chart-row-81"]/div[7]/div/a',
        '11': '//*[@id="chart-row-82"]/div[3]/div/a',
        '12': '//*[@id="chart-row-83"]/div[3]/div/a',
        '13': '//*[@id="chart-row-84"]/div[2]/div/a',
        '14': '//*[@id="chart-row-85"]/div[3]/div/a',
        '15': '//*[@id="chart-row-86"]/div[4]/div/a',
        '16': '//*[@id="chart-row-87"]/div[2]/div/a',
        '2': '//*[@id="chart-row-88"]/div[5]/div/a',
        '21': '//*[@id="chart-row-89"]/div[3]/div/a',
        '22': '//*[@id="chart-row-90"]/div[2]/div/a',
        '23': '//*[@id="chart-row-91"]/div[2]/div/a',
        '24': '//*[@id="chart-row-92"]/div[2]/div/a',
        '25': '//*[@id="chart-row-93"]/div[3]/div/a',
        '26': '//*[@id="chart-row-94"]/div[2]/div/a',
        '3': '//*[@id="chart-row-95"]/div[2]/div/a',
        '31': '//*[@id="chart-row-96"]/div[2]/div/a',
        '32': '//*[@id="chart-row-97"]/div[2]/div/a',
        '33': '//*[@id="chart-row-98"]/div/div/a',
        '34': '//*[@id="chart-row-99"]/div[3]/div/a',
        '35': '//*[@id="chart-row-100"]/div[2]/div/a',
    }
}